name = "leantest"
version = "0.1.0"
defaultTargets = ["leantest"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.26.0"

[[lean_lib]]
name = "Leantest"

[[lean_exe]]
name = "leantest"
root = "Main"
